/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef FlowPipe_CONSTANTS_H
#define FlowPipe_CONSTANTS_H

#include "FlowPipe_types.h"

namespace flow {

class FlowPipeConstants {
 public:
  FlowPipeConstants();

};

extern const FlowPipeConstants g_FlowPipe_constants;

} // namespace

#endif
