// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "FlowPipe.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::flow;

class FlowPipeHandler : virtual public FlowPipeIf {
 public:
  FlowPipeHandler() {
    // Your initialization goes here
  }

  bool initiate(const int32_t clientId) {
    // Your implementation goes here
    printf("initiate\n");
  }

  bool reset(const int32_t clientId) {
    // Your implementation goes here
    printf("reset\n");
  }

  bool close(const int32_t clientId) {
    // Your implementation goes here
    printf("close\n");
  }

  bool sendHeartbeat(const int32_t clientId) {
    // Your implementation goes here
    printf("sendHeartbeat\n");
  }

  void getConfig(std::string& _return, const int32_t clientId) {
    // Your implementation goes here
    printf("getConfig\n");
  }

  void send(const int32_t clientId, const Object& object) {
    // Your implementation goes here
    printf("send\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<FlowPipeHandler> handler(new FlowPipeHandler());
  shared_ptr<TProcessor> processor(new FlowPipeProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

